// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvControl.API.DataLayer;

namespace TvControl.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200109202137_RemoveMovieFromGenre")]
    partial class RemoveMovieFromGenre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TvControl.API.Models.Contributor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("MovieID");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("TvControl.API.Models.ContributorType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContributorID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ContributorID");

                    b.ToTable("ContributorTypes");
                });

            modelBuilder.Entity("TvControl.API.Models.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("MovieID");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("TvControl.API.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContributorID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ContributorID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("TvControl.API.Models.Contributor", b =>
                {
                    b.HasOne("TvControl.API.Models.Movie")
                        .WithMany("Contributors")
                        .HasForeignKey("MovieID");
                });

            modelBuilder.Entity("TvControl.API.Models.ContributorType", b =>
                {
                    b.HasOne("TvControl.API.Models.Contributor")
                        .WithMany("ContributorTypes")
                        .HasForeignKey("ContributorID");
                });

            modelBuilder.Entity("TvControl.API.Models.Genre", b =>
                {
                    b.HasOne("TvControl.API.Models.Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieID");
                });

            modelBuilder.Entity("TvControl.API.Models.Movie", b =>
                {
                    b.HasOne("TvControl.API.Models.Contributor")
                        .WithMany("Movies")
                        .HasForeignKey("ContributorID");
                });
#pragma warning restore 612, 618
        }
    }
}
